### ISSUE TITLE
No van a enseñar R?

### ISSUE THREAD

**Issue by Eflores89** [ricalanis/Programa-Data-Science#13]

**Comment by ricalanis** [comment]
En 7 semanas, es complicado entrar a suficiente detalle y al mismo tiempo detallar dos lenguajes de programación. Durante estas 7 semanas queremos que las personas se lleven un panorama completo de la ciencia de datos y escogimos enfocarnos a Python para también entrar a detalle sobre como desarrollar bien en este lenguaje (De ahi la primer semana)

Una alternativa, es el proveer de material para aprender no solo R, sino también Scala para trabajar en Big data, o C++ para data science que puede ser útil.

**Comment by Eflores89** [comment]
fair enough! :+1: 

Estaba solo curioso. Si arman luego uno con **R**, podría aportar!
